UBUNTU: SAUCE: i915: Fix build error due to missing struct definition
FTBFS in v5.9-rc1:

 In file included from /tmp/kernel-sforshee-f5108e59edd8-jyEs/build/drivers/gpu/drm/i915/i915_active.h:12,
                  from /tmp/kernel-sforshee-f5108e59edd8-jyEs/build/drivers/gpu/drm/i915/gt/intel_context_param.c:6:
 /tmp/kernel-sforshee-f5108e59edd8-jyEs/build/drivers/gpu/drm/i915/i915_active_types.h:35:22: error: field 'rwsem' has incomplete type
    35 |  struct rw_semaphore rwsem;
       |                      ^~~~~

Fix by adding an include to provide the definition.

Signed-off-by: Seth Forshee <seth.forshee@canonical.com>